---
- name: Install yum-cron
  yum: name=yum-cron state=latest

- name: Enable auto update
  lineinfile:
    dest: /etc/yum/yum-cron.conf
    backrefs: yes
    regexp: "^apply_updates ="
    line: "apply_updates = yes"
  notify: restart yum-cron

- name: Set emit_via
  lineinfile:
    dest: /etc/yum/yum-cron.conf
    backrefs: yes
    regexp: "^emit_via ="
    line: "emit_via = stdio,email"
  notify: restart yum-cron

- name: Enable notify mail
  lineinfile:
    dest: /etc/yum/yum-cron.conf
    backrefs: yes
    regexp: "^email_to ="
    line: "email_to = {{ administrator_email }}"
  notify: restart yum-cron

- name: Start yum-cron
  service:
    name: yum-cron
    state: started
    enabled: yes
